language: ruby
rvm:
  - 2.2.3
  - 1.9.3
  - jruby-9.0.0.0
  - jruby-1.7.20
  - rbx
before_install:
 - 'if [ "$TRAVIS_RUBY_VERSION" = "jruby-9.0.0.0" ]; then rvm get head && rvm reload && rvm install $TRAVIS_RUBY_VERSION && rvm use $TRAVIS_RUBY_VERSION; fi'
 - gem install bundler -v 1.10.5
